version: "3"
services:
  postgres:
    image: postgres
  rabbitmq:
    image: rabbitmq
  apache:
    image: httpd
    ports:
      - 8000:80
  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000